version: '3.4'
services:

    profile-builder:
        image: node:9.9
        networks:
            - frontend
        volumes:
            - ./services:/usr/src/app
        environment:
            NODE_ENV: production
            LOG_LEVEL: ${LOG_LEVEL-info}
            PG_HOST: ${PG_HOST-postgres}
            PG_PORT: ${PG_PORT-5432}
            PG_USERNAME: ${PG_USERNAME-cerberus}
            PG_PASSWORD: ${PG_PASSWORD-cerberus}
            PG_DATABASE: ${PG_DATABASE-cerberus}
            STORAGE_PG_HOST: ${STORAGE_PG_HOST-postgres}
            STORAGE_PG_PORT: ${STORAGE_PG_PORT-5432}
            STORAGE_PG_USERNAME: ${STORAGE_PG_USERNAME-cerberus}
            STORAGE_PG_PASSWORD: ${STORAGE_PG_PASSWORD-cerberus}
            STORAGE_PG_DATABASE: ${STORAGE_PG_DATABASE-cerberus}
            API_ENDPOINT: ${API_ENDPOINT-http://localhost:8080/api}
            API_TOKEN: ${API_TOKEN-test-token}
        working_dir: /usr/src/app/profile-builder
        entrypoint: ["yarn", "start:prod"]

#
# Networks definition
#

networks:
    frontend:
