version: '3.4'
services:

#
# INFRASTRUCTURE
# - humble boot services
# - humble drop services
#

    postgres:
        image: fetchq/fetchq:10.4-1.3.0
        ports:
            - ${PG_PORT:-5432}:5432
        networks:
            - frontend
        environment:
            POSTGRES_USER: ${PG_USERNAME:-cerberus}
            POSTGRES_PASSWORD: ${PG_PASSWORD:-cerberus}
            POSTGRES_DB: ${PG_DATABASE:-cerberus}
        volumes:
            - ${HUMBLE_DATA}/pg:/var/lib/postgresql/data
            - ${HUMBLE_BACKUP}:/backup
        restart: always

#
# REAL WORKER PROCESSES
#

    discovery:
        image: node:9.9
        networks:
            - frontend
        volumes:
            - ./services:/usr/src/app
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL-info}
            PG_HOST: ${PG_HOST-postgres}
            PG_PORT: ${PG_PORT-5432}
            PG_USERNAME: ${PG_USERNAME-cerberus}
            PG_PASSWORD: ${PG_PASSWORD-cerberus}
            PG_DATABASE: ${PG_DATABASE-cerberus}
            PG_MAX_CONN_ATTEMPTS: ${PG_MAX_CONN_ATTEMPTS-10}
            PG_CONN_ATTEMPTS_DELAY: ${PG_CONN_ATTEMPTS_DELAY-10}
            PG_DEBUG: ${PG_DEBUG-off}
            STORAGE_PG_HOST: ${STORAGE_PG_HOST-postgres}
            STORAGE_PG_PORT: ${STORAGE_PG_PORT-1234}
            STORAGE_PG_USERNAME: ${STORAGE_PG_USERNAME-cerberus}
            STORAGE_PG_PASSWORD: ${STORAGE_PG_PASSWORD-cerberus}
            STORAGE_PG_DATABASE: ${STORAGE_PG_DATABASE-cerberus}
            STORAGE_PG_MAX_CONN_ATTEMPTS: ${STORAGE_PG_MAX_CONN_ATTEMPTS-10}
            STORAGE_PG_CONN_ATTEMPTS_DELAY: ${STORAGE_PG_CONN_ATTEMPTS_DELAY-10}
            STORAGE_PG_DEBUG: ${STORAGE_PG_DEBUG-off}
        working_dir: /usr/src/app/discovery
        entrypoint: ["yarn", "start:dev"]

    first-blood:
        image: node:9.9
        networks:
            - frontend
        volumes:
            - ./services:/usr/src/app
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL-info}
            PG_HOST: ${PG_HOST-postgres}
            PG_PORT: ${PG_PORT-5432}
            PG_USERNAME: ${PG_USERNAME-cerberus}
            PG_PASSWORD: ${PG_PASSWORD-cerberus}
            PG_DATABASE: ${PG_DATABASE-cerberus}
            PG_MAX_CONN_ATTEMPTS: ${PG_MAX_CONN_ATTEMPTS-10}
            PG_CONN_ATTEMPTS_DELAY: ${PG_CONN_ATTEMPTS_DELAY-10}
            PG_DEBUG: ${PG_DEBUG-off}
            STORAGE_PG_HOST: ${STORAGE_PG_HOST-postgres}
            STORAGE_PG_PORT: ${STORAGE_PG_PORT-1234}
            STORAGE_PG_USERNAME: ${STORAGE_PG_USERNAME-cerberus}
            STORAGE_PG_PASSWORD: ${STORAGE_PG_PASSWORD-cerberus}
            STORAGE_PG_DATABASE: ${STORAGE_PG_DATABASE-cerberus}
            STORAGE_PG_MAX_CONN_ATTEMPTS: ${STORAGE_PG_MAX_CONN_ATTEMPTS-10}
            STORAGE_PG_CONN_ATTEMPTS_DELAY: ${STORAGE_PG_CONN_ATTEMPTS_DELAY-10}
            STORAGE_PG_DEBUG: ${STORAGE_PG_DEBUG-off}
        working_dir: /usr/src/app/first-blood
        entrypoint: ["yarn", "start:dev"]

    profile-tracker:
        image: node:9.9
        networks:
            - frontend
        volumes:
            - ./services:/usr/src/app
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL-info}
            PG_HOST: ${PG_HOST-postgres}
            PG_PORT: ${PG_PORT-5432}
            PG_USERNAME: ${PG_USERNAME-cerberus}
            PG_PASSWORD: ${PG_PASSWORD-cerberus}
            PG_DATABASE: ${PG_DATABASE-cerberus}
            PG_MAX_CONN_ATTEMPTS: ${PG_MAX_CONN_ATTEMPTS-10}
            PG_CONN_ATTEMPTS_DELAY: ${PG_CONN_ATTEMPTS_DELAY-10}
            PG_DEBUG: ${PG_DEBUG-off}
            STORAGE_PG_HOST: ${STORAGE_PG_HOST-postgres}
            STORAGE_PG_PORT: ${STORAGE_PG_PORT-1234}
            STORAGE_PG_USERNAME: ${STORAGE_PG_USERNAME-cerberus}
            STORAGE_PG_PASSWORD: ${STORAGE_PG_PASSWORD-cerberus}
            STORAGE_PG_DATABASE: ${STORAGE_PG_DATABASE-cerberus}
            STORAGE_PG_MAX_CONN_ATTEMPTS: ${STORAGE_PG_MAX_CONN_ATTEMPTS-10}
            STORAGE_PG_CONN_ATTEMPTS_DELAY: ${STORAGE_PG_CONN_ATTEMPTS_DELAY-10}
            STORAGE_PG_DEBUG: ${STORAGE_PG_DEBUG-off}
        working_dir: /usr/src/app/profile-tracker
        entrypoint: ["yarn", "start:dev"]

    post-tracker:
        image: node:9.9
        networks:
            - frontend
        volumes:
            - ./services:/usr/src/app
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL-info}
            PG_HOST: ${PG_HOST-postgres}
            PG_PORT: ${PG_PORT-5432}
            PG_USERNAME: ${PG_USERNAME-cerberus}
            PG_PASSWORD: ${PG_PASSWORD-cerberus}
            PG_DATABASE: ${PG_DATABASE-cerberus}
            PG_MAX_CONN_ATTEMPTS: ${PG_MAX_CONN_ATTEMPTS-10}
            PG_CONN_ATTEMPTS_DELAY: ${PG_CONN_ATTEMPTS_DELAY-10}
            PG_DEBUG: ${PG_DEBUG-off}
            STORAGE_PG_HOST: ${STORAGE_PG_HOST-postgres}
            STORAGE_PG_PORT: ${STORAGE_PG_PORT-1234}
            STORAGE_PG_USERNAME: ${STORAGE_PG_USERNAME-cerberus}
            STORAGE_PG_PASSWORD: ${STORAGE_PG_PASSWORD-cerberus}
            STORAGE_PG_DATABASE: ${STORAGE_PG_DATABASE-cerberus}
            STORAGE_PG_MAX_CONN_ATTEMPTS: ${STORAGE_PG_MAX_CONN_ATTEMPTS-10}
            STORAGE_PG_CONN_ATTEMPTS_DELAY: ${STORAGE_PG_CONN_ATTEMPTS_DELAY-10}
            STORAGE_PG_DEBUG: ${STORAGE_PG_DEBUG-off}
        working_dir: /usr/src/app/post-tracker
        entrypoint: ["yarn", "start:dev"]

#
# Networks definition
#

networks:
    frontend:
