version: '3.4'
services:

    grafana:
        image: grafana/grafana:5.0.4
        ports:
            - ${GRAFANA_PORT-5555}:3000
        environment:
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD-mysocial}
        volumes:
            - ${HUMBLE_DATA}:/var/lib/grafana