
#
### NODE CONFIG
#

setup:
	cp ../root/src/boot.js ./src/boot.js

	cp ../root/.env ./.env
	cp ../root/package.json ./package.json
	cp ../root/yarn.lock ./yarn.lock
	cp ../root/index.js ./index.js
	cp ../root/docker-compose.yml ./docker-compose.yml
	cp ../root/Dockerfile ./Dockerfile

	cp -a ../root/src/features/ ./src/features/
	cp -a ../root/src/services/ ./src/services/
	cp -a ../root/src/lib/ ./src/lib/

refresh:
	cp ../root/.env ./.env
	cp ../root/package.json ./package.json
	cp ../root/yarn.lock ./yarn.lock
	cp ../root/index.js ./index.js
	cp ../root/docker-compose.yml ./docker-compose.yml
	cp ../root/Dockerfile ./Dockerfile

	cp -a ../root/src/features/ ./src/features/
	cp -a ../root/src/services/ ./src/services/
	cp -a ../root/src/lib/ ./src/lib/
