
#
### NODE CONFIG
#

setup:
	cp ../../root-node/src/boot.js ./src/boot.js

	cp ../../root-node/.env ./.env
	cp ../../root-node/package.json ./package.json
	cp ../../root-node/index.js ./index.js

	cp -a ../../root-node/src/features/ ./src/features/
	cp -a ../../root-node/src/services/ ./src/services/
	cp -a ../../root-node/src/lib/ ./src/lib/

refresh:
	cp ../../root-node/.env ./.env
	cp ../../root-node/package.json ./package.json
	cp ../../root-node/index.js ./index.js

	cp -a ../../root-node/src/features/ ./src/features/
	cp -a ../../root-node/src/services/ ./src/services/
	cp -a ../../root-node/src/lib/ ./src/lib/
